import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — I Ching Hexagram & Yearly Fortune Reading',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0b0e] text-[#e2d9c8] font-serif px-4 py-12 md:px-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-xs text-[#d4af37] hover:underline">&larr; Back to home</Link>
        <h1 className="text-3xl font-bold text-[#f3ece0] mt-4 mb-2">Terms of Service</h1>
        <p className="text-xs text-[#8c8577] mb-10">Last updated: August 2026</p>

        <div className="space-y-8 text-sm text-[#c5bcac] leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">1. About this service</h2>
            <p>
              I Ching Hexagram &amp; Yearly Fortune Reading ("the Service," "we," "us") is a web application
              that generates a personalized I Ching (Yijing) hexagram reading and yearly forecast based on
              birth information you provide. By using the Service, you agree to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">2. Entertainment and self-reflection purposes only</h2>
            <p>
              The Service is provided for entertainment, cultural interest, and personal reflection purposes only.
              It does not constitute — and should not be relied upon as — professional advice of any kind, including
              but not limited to financial, medical, legal, or psychological advice. Any decisions you make based on
              your reading are made at your own discretion and risk. If you are facing a medical, legal, financial,
              or mental health matter, please consult an appropriately qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">3. Accuracy of content</h2>
            <p>
              The classical hexagram text used in this Service is drawn from the original Zhouyi (I Ching), a public
              domain classical text. Interpretive commentary, English translations of hexagram names, and generated
              forecast text are produced algorithmically and are intended as a general reading aid. We make no
              warranty as to the completeness, accuracy, or fitness for any particular purpose of any content
              generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">4. Payment and Merchant of Record</h2>
            <p>
              Purchases made through the Service are processed by our online reseller and Merchant of Record,
              Gumroad, Inc. ("Gumroad"), San Francisco, California, USA. Gumroad handles payment processing, tax
              collection and remittance, and related customer service inquiries for your order, including refund
              requests. See our{' '}
              <Link href="/refund" className="text-[#d4af37] underline">Refund Policy</Link> for details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">5. No account, no stored results</h2>
            <p>
              The Service does not require account registration. A completed reading exists only in your browser
              session for that visit and is not stored on our servers. If you purchase the full reading, you are
              responsible for saving or downloading your results before closing the page — see the on-screen
              prompt after purchase. We cannot restore a lost reading without a new purchase.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">6. Eligibility</h2>
            <p>
              The Service is intended for users aged 18 and older, or the age of legal majority in your
              jurisdiction. By using the Service, you confirm that you meet this requirement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">7. Changes to these Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes are posted
              constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#d4af37] mb-2">8. Contact</h2>
            <p>
              Questions about these Terms can be sent to{' '}
              <span className="text-[#d4af37]">[your-support-email@example.com]</span>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
